import { mkdir, mkdtemp, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { EnrichedRepo } from "../schema/github.js";

export const GENERATED_FILENAMES = [
  "AWESOME-MCP-REPOS.md",
  "TOP-TENS.md",
  "ACTIVITY.md",
  "README.md",
  "INDEX-COVERAGE.md",
  "data/indexes.json",
  "data/discovery-audit.json",
  "data/index-links.json",
] as const;

export type GeneratedFilename = (typeof GENERATED_FILENAMES)[number];
export type GeneratedOutputs = Record<GeneratedFilename, string>;

export function validateGeneratedOutputs(
  repos: EnrichedRepo[],
  outputs: GeneratedOutputs,
  minimumRepoCount: number,
): void {
  if (!Number.isSafeInteger(minimumRepoCount) || minimumRepoCount < 1) {
    throw new Error("The minimum repository count must be a positive integer");
  }

  if (repos.length < minimumRepoCount) {
    throw new Error(
      `Refusing to publish ${repos.length} repositories; expected at least ${minimumRepoCount}`,
    );
  }

  for (const filename of GENERATED_FILENAMES) {
    const content = outputs[filename];
    if (!content || content.trim().length < 100) {
      throw new Error(`Refusing to publish empty or unexpectedly small ${filename}`);
    }
  }

  const readme = outputs["README.md"];
  const startMarker = "<!-- AUTO-GENERATED BY find-awesome-mcp-servers SCRIPT -->";
  const endMarker = "<!-- END AUTO-GENERATED -->";
  if (!readme.includes(startMarker) || !readme.includes(endMarker)) {
    throw new Error("Generated README.md is missing its index markers");
  }
}

export async function writeGeneratedOutputs(
  outputDir: string,
  outputs: GeneratedOutputs,
): Promise<void> {
  const temporaryDir = await mkdtemp(join(outputDir, ".index-build-"));

  try {
    await Promise.all(
      GENERATED_FILENAMES.map(async (filename) => {
        const temporaryPath = join(temporaryDir, filename);
        await mkdir(dirname(temporaryPath), { recursive: true });
        await writeFile(temporaryPath, outputs[filename], "utf8");
      }),
    );

    for (const filename of GENERATED_FILENAMES) {
      const outputPath = join(outputDir, filename);
      await mkdir(dirname(outputPath), { recursive: true });
      await rename(join(temporaryDir, filename), outputPath);
    }
  } finally {
    await rm(temporaryDir, { recursive: true, force: true });
  }
}
