import { readFileSync } from "fs";
import { EnrichedRepo } from "../schema/github.js";
import { repoLink, sanitizeDescription } from "../utils/format.js";
import {
  centeredHeader,
  dashboardGrid,
  githubAlert,
  licenseDistribution,
  mermaidPieChart,
} from "./components.js";
import { navigationBar, pageFooter } from "./navigation.js";
import { BADGE_STYLE, COLORS, LEADERBOARD_COPY } from "./theme.js";

const TABLE_HEADER = [
  "| Repository | Stars | Forks | License | Created | Updated | Description |",
  "| ---------- | ----: | ----: | ------- | ------- | ------- | ----------- |",
];

function allReposRow(repo: EnrichedRepo): string {
  const link = repoLink(repo);
  const stars = repo.stargazers_count.toLocaleString();
  const forks = repo.forks_count.toLocaleString();
  const license = repo.license?.name ?? "-";
  const created = repo.created_at.split("T")[0];
  const updated = repo.pushed_at.split("T")[0];
  const description = sanitizeDescription(repo.description);

  return `| ${link} | ${stars} | ${forks} | ${license} | ${created} | ${updated} | ${description} |`;
}

export function generateAllReposPage(repos: EnrichedRepo[]): string {
  const copy = LEADERBOARD_COPY.allRepos;
  const generatedDate = new Date().toISOString().split("T")[0];
  const licenseDist = licenseDistribution(repos);

  const sections = [
    navigationBar("allRepos"),
    centeredHeader(copy, generatedDate),
    dashboardGrid([
      {
        label: "Total Repositories",
        value: repos.length,
        color: COLORS.totalRepos,
      },
      {
        label: "Combined Stars",
        value: `${Math.round(repos.reduce((sum, r) => sum + r.stargazers_count, 0) / 1000)}k+`,
        color: COLORS.starred,
      },
      {
        label: "Combined Forks",
        value: `${Math.round(repos.reduce((sum, r) => sum + r.forks_count, 0) / 1000)}k+`,
        color: COLORS.forked,
      },
    ]),
    "",
    githubAlert(
      "NOTE",
      "This table shows every awesome-mcp repository discovered on GitHub. Updated daily via GitHub Actions.",
    ),
    "",
    "<details>",
    "<summary><b>License Distribution</b></summary>",
    "",
    mermaidPieChart("Repos by License", licenseDist),
    "",
    "</details>",
    "",
    ...TABLE_HEADER,
    ...repos.map(allReposRow),
    pageFooter(),
  ];

  return sections.join("\n");
}

function buildReadmeIndexBlock(repoCount: number): string {
  const updatedDate = new Date().toISOString().split("T")[0];

  const statBadges = [
    `![Total Repos](https://img.shields.io/badge/Total_Repos-${repoCount}-${COLORS.totalRepos}?style=${BADGE_STYLE.header})`,
    `![Last Updated](https://img.shields.io/badge/Updated-${updatedDate.replace(/-/g, "--")}-${COLORS.generated}?style=${BADGE_STYLE.header})`,
  ].join(" ");

  const navEntries = (
    [
      "topStarred",
      "topForked",
      "topSubscribed",
      "topIssues",
      "topLargest",
      "activity",
    ] as const
  ).map((id) => {
    const copy = LEADERBOARD_COPY[id];
    const label = encodeURIComponent(`${copy.icon} ${copy.badgeLabel}`);
    return `      <a href="./${copy.filename}">
        <img src="https://img.shields.io/badge/${label}-${copy.badgeColor}?style=${BADGE_STYLE.header}" /><br>
        <sub><b>${copy.badgeLabel}</b></sub>
      </a>`;
  });

  const allReposCopy = LEADERBOARD_COPY.allRepos;
  const allReposLabel = encodeURIComponent(
    `${allReposCopy.icon} ${allReposCopy.badgeLabel}`,
  );

  return [
    `<div align="center">`,
    "",
    statBadges,
    "",
    "</div>",
    "",
    `> [!NOTE]`,
    `> This index is auto-updated daily via GitHub Actions. Data sourced from the GitHub API.`,
    "",
    "<table>",
    "  <tr>",
    navEntries.slice(0, 3).join("\n    <td>&nbsp;&nbsp;</td>\n"),
    "  </tr>",
    "  <tr>",
    navEntries.slice(3).join("\n    <td>&nbsp;&nbsp;</td>\n"),
    "  </tr>",
    "</table>",
    "",
    `<div align="center">`,
    "",
    `[![${allReposCopy.badgeLabel}](https://img.shields.io/badge/${allReposLabel}-${allReposCopy.badgeColor}?style=${BADGE_STYLE.header}&logo=github&logoColor=white)](./${allReposCopy.filename})`,
    "",
    "</div>",
  ].join("\n");
}

export function updateReadmeWithIndex(
  readmePath: string,
  repoCount: number,
): string {
  const existingReadme = readFileSync(readmePath, "utf-8");
  const startMarker =
    "<!-- AUTO-GENERATED BY find-awesome-mcp-servers SCRIPT -->";
  const endMarker = "<!-- END AUTO-GENERATED -->";

  const startIndex = existingReadme.indexOf(startMarker);
  const endIndex = existingReadme.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1) {
    throw new Error("Could not find AUTO-GENERATED markers in README.md");
  }

  const before = existingReadme.slice(0, startIndex + startMarker.length);
  const after = existingReadme.slice(endIndex);
  const indexBlock = buildReadmeIndexBlock(repoCount);

  return `${before}\n\n${indexBlock}\n\n${after}`;
}
