import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  GeneratedOutputs,
  validateGeneratedOutputs,
  writeGeneratedOutputs,
} from "../generation/output.js";
import { EnrichedRepo } from "../schema/github.js";

function outputs(): GeneratedOutputs {
  const content = "# Generated\n\n" + "content ".repeat(20);
  return {
    "AWESOME-MCP-REPOS.md": content,
    "TOP-TENS.md": content,
    "ACTIVITY.md": content,
    "README.md": [
      "# Index",
      "<!-- AUTO-GENERATED BY find-awesome-mcp-servers SCRIPT -->",
      content,
      "<!-- END AUTO-GENERATED -->",
    ].join("\n"),
    "INDEX-COVERAGE.md": content,
    "data/indexes.json": content,
    "data/discovery-audit.json": content,
    "data/index-links.json": content,
  };
}

test("validation refuses an unexpectedly small index", () => {
  const repos = [{}] as EnrichedRepo[];
  assert.throws(
    () => validateGeneratedOutputs(repos, outputs(), 2),
    /Refusing to publish 1 repositories/,
  );
});

test("validated outputs are written together", async () => {
  const outputDir = await mkdtemp(join(tmpdir(), "mcp-index-output-"));
  const generated = outputs();

  try {
    validateGeneratedOutputs([{}] as EnrichedRepo[], generated, 1);
    await writeGeneratedOutputs(outputDir, generated);

    for (const [filename, expected] of Object.entries(generated)) {
      assert.equal(await readFile(join(outputDir, filename), "utf8"), expected);
    }
  } finally {
    await rm(outputDir, { recursive: true, force: true });
  }
});
